# Generated by Django 5.1.1 on 2024-10-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_rename_director_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=(('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****'))),
        ),
    ]
